timezone: "Asia/Shanghai"
log: "./log"
timeout: 20
comms:
  - command: "curl"
    args: "http://0.0.0.0:8000?a=11"
    cron: "*/3 * * * * *"
  # - command: "echo"
  #   args: "Hello World!"
  #   cron: "*/3 * * * * *"
  # - command: "date"
  #   args: "+%Y-%m-%d %H:%M:%S"
  #   cron: "0 0 * * * *"
